### ISSUE TITLE
Different behaviour when connecting through WiFi or GSM

### ISSUE THREAD

**Issue by mlspoelstra** [khoih-prog/Blynk_Async_GSM_Manager#5]
I use this Blynk_Async_GSM_Manager to connect to Blynk through either WiFi or GSM with a TTGO T-Call. 

I've noticed that when I connect through WiFi then I can't use the terminalprintln function of Blynk. I need to use Blynk.virtualWrite to write info to the terminal in the mobile App.

However, when I connect through GSM then I can use terminalprintln, but Blynk.virtualWrite doesn't work any more.

**Comment by khoih-prog** [comment]
Thanks for using the library.

That behaviour, IMO, is dictated by `Blynk` as this library is just a wrapper around `Blynk`.

If possible, you have to provide more details as expected and requested in [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example) so that anybody interested can have some basic info.

I also suggest that you post an issue in [**Blynk issue**](https://github.com/blynkkk/blynk-library/issues) or [**Blynk Community Forum**](https://community.blynk.cc/) to ask for help.

I'm currently not actively spend my time with my `Blynk libraries` anymore as I have some other more interesting fields / boards to do. 

Sorry, unless you prove this is a severe bug of the library, I'm not going to spend time with this issue and closing it now.

Good Luck,

**Comment by mlspoelstra** [comment]
Thanks for the reply. I'll look for a workaround.
Really enjoy many aspects of your library and hope to keep using it.

Sent from Yahoo Mail on Android 
 
  On Fri, 10 Sep 2021 at 19:39, Khoi ***@***.***> wrote:   


Thanks for using the library.

That behaviour, IMO, is dictated by Blynk as this library is just a wrapper around Blynk.

If possible, you have to provide more details as expected and requested in MRE so that anybody interested can have some basic info.

I also suggest that you post an issue in Blynk issue or Blynk Community Forum to ask for help.

I'm currently not actively spend my time with my Blynk libraries anymore as I have some other more interesting fields / boards to do.

Sorry, unless you prove this is a severe bug of the library, I'm not going to spend time with this issue and closing it now.

Good Luck,

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
